# Generated by Django 6.0.4 on 2026-04-10 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', '待付款'), ('paid', '已付款'), ('processing', '處理中'), ('shipped', '已出貨'), ('delivered', '已到貨'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending_payment', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('failed', '付款失敗'), ('refunded', '已退款')], default='pending', max_length=20)),
                ('logistics_type', models.CharField(blank=True, choices=[('home', '宅配'), ('cvs', '超商取貨')], max_length=10, null=True)),
                ('logistics_status', models.CharField(choices=[('pending', '待處理'), ('created', '已建立'), ('in_transit', '運送中'), ('arrived', '已到達'), ('delivered', '已取貨'), ('failed', '配送失敗')], default='pending', max_length=20)),
                ('tracking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_address', models.JSONField(blank=True, null=True)),
                ('cvs_store_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cvs_store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cvs_type', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': '訂單項目',
                'verbose_name_plural': '訂單項目',
                'db_table': 'order_items',
            },
        ),
    ]
