# Generated by Django 6.0.4 on 2026-04-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_zh', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('summary_zh', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', '上架'), ('inactive', '下架'), ('out_of_stock', '缺貨')], default='active', max_length=20)),
                ('images', models.JSONField(default=list)),
                ('stock', models.IntegerField(default=0)),
                ('unlimited_stock', models.BooleanField(default=False)),
                ('has_variants', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(default=list)),
                ('promo_label', models.CharField(blank=True, max_length=255, null=True)),
                ('promo_label_zh', models.CharField(blank=True, max_length=255, null=True)),
                ('hide_price', models.BooleanField(default=False)),
                ('is_preorder', models.BooleanField(default=False)),
                ('preorder_note', models.TextField(blank=True, null=True)),
                ('preorder_note_zh', models.TextField(blank=True, null=True)),
                ('exclude_from_discount', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_zh', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_description_zh', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('available_start', models.DateTimeField(blank=True, null=True)),
                ('available_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': '商品規格',
                'verbose_name_plural': '商品規格',
                'db_table': 'product_variants',
            },
        ),
    ]
